"""empty message

Revision ID: c18a87f0197f
Revises: c059049d547d
Create Date: 2023-05-17 19:36:13.633339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18a87f0197f'
down_revision = 'c059049d547d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('height', sa.String(length=20), nullable=False),
    sa.Column('mass', sa.String(length=20), nullable=False),
    sa.Column('home', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('favorite_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('gravity', sa.String(length=25), nullable=False),
    sa.Column('population', sa.String(length=25), nullable=False),
    sa.Column('climate', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Numeric(precision=25, scale=0), nullable=False),
    sa.Column('pilots', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
#     op.drop_table('address')
#     op.drop_table('blog_post')
#     op.drop_table('comment')
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
#         batch_op.alter_column('firstname',
#                existing_type=sa.VARCHAR(length=250),
#                type_=sa.String(length=25),
#                existing_nullable=False)
#         batch_op.alter_column('lastname',
#                existing_type=sa.VARCHAR(length=250),
#                type_=sa.String(length=25),
#                existing_nullable=False)
#         batch_op.alter_column('email',
#                existing_type=sa.VARCHAR(length=250),
#                type_=sa.String(length=25),
#                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
                              existing_type=sa.String(length=25),
                              type_=sa.VARCHAR(length=250),
                              existing_nullable=False)
        batch_op.alter_column('lastname',
                              existing_type=sa.String(length=25),
                              type_=sa.VARCHAR(length=250),
                              existing_nullable=False)
        batch_op.alter_column('firstname',
                              existing_type=sa.String(length=25),
                              type_=sa.VARCHAR(length=250),
                              existing_nullable=False)
        batch_op.drop_column('is_active')

#     op.create_table('comment',
#                     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#                     sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
#                     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#                     sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
#                     sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], name='comment_post_id_fkey'),
#                     sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_user_id_fkey'),
#                     sa.PrimaryKeyConstraint('id', name='comment_pkey')
#                     )
#     op.create_table('blog_post',
#                     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#                     sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#                     sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
#                     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#                     sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='blog_post_user_id_fkey'),
#                     sa.PrimaryKeyConstraint('id', name='blog_post_pkey')
#                     )
#     op.create_table('address',
#                     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#                     sa.Column('street_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
#                     sa.Column('street_number', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
#                     sa.Column('post_code', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
#                     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#                     sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='address_user_id_fkey'),
#                     sa.PrimaryKeyConstraint('id', name='address_pkey')
#                     )
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('favorites')
    op.drop_table('characters')
    # ### end Alembic commands ###